name: Ultra Monitor A

on:
  schedule:
    # Every minute at seconds 0, 10, 20, 30, 40, 50
    - cron: '* * * * *'  # Every minute - will handle 10-second intervals in Python
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Ultra-fast monitoring
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_ACTIONS: 'true'
          MONITOR_ID: 'A'
        run: |
          python -c "
          import asyncio
          import time
          import aiohttp
          import os
          from datetime import datetime
          
          DISCORD_WEBHOOK_URL = os.getenv('DISCORD_WEBHOOK_URL')
          URL = 'https://results.beup.ac.in/BTech5thSem2024_B2022Results.aspx'
          MONITOR_ID = os.getenv('MONITOR_ID', 'A')
          
          async def quick_check():
              try:
                  async with aiohttp.ClientSession() as session:
                      # Check 6 times in 50 seconds (every 10 seconds)
                      for i in range(6):
                          start_time = time.time()
                          
                          try:
                              async with session.get(URL, timeout=aiohttp.ClientTimeout(total=8)) as resp:
                                  status = 'UP' if resp.status == 200 else 'DOWN'
                              
                              # Send quick update only if DOWN or every 3rd check when UP
                              if status == 'DOWN' or i % 3 == 0:
                                  timestamp = datetime.now().strftime('%H:%M:%S')
                                  payload = {
                                      'content': f'🔍[{MONITOR_ID}] {status} [{timestamp}] (Check {i+1}/6)',
                                      'username': f'Ultra Monitor {MONITOR_ID}'
                                  }
                                  
                                  try:
                                      async with session.post(DISCORD_WEBHOOK_URL, json=payload, timeout=5) as discord_resp:
                                          if discord_resp.status == 429:  # Rate limited
                                              await asyncio.sleep(1)
                                  except:
                                      pass  # Ignore Discord errors to keep monitoring
                                      
                          except asyncio.TimeoutError:
                              # Site timeout - send alert
                              timestamp = datetime.now().strftime('%H:%M:%S')
                              payload = {
                                  'content': f'⏱️[{MONITOR_ID}] TIMEOUT [{timestamp}] (Check {i+1}/6)',
                                  'username': f'Ultra Monitor {MONITOR_ID}'
                              }
                              try:
                                  async with session.post(DISCORD_WEBHOOK_URL, json=payload, timeout=5) as discord_resp:
                                      pass
                              except:
                                  pass
                          
                          # Wait exactly 10 seconds between checks
                          elapsed = time.time() - start_time
                          wait_time = max(0, 10 - elapsed)
                          if i < 5:  # Don't wait after last check
                              await asyncio.sleep(wait_time)
                              
              except Exception as e:
                  print(f'Monitor {MONITOR_ID} error: {e}')
          
          asyncio.run(quick_check())
          "